---
title: "stl_lead_inequality"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(here)

```
```{r}
stl_blood = read_delim(here::here("data", "stl_blood_lead.csv")) %>% 
  janitor::clean_names() %>% 
  mutate(prop_white = (white / total_pop) * 100) %>% 
  mutate(pct_elevated = str_replace(pct_elevated,
                                    pattern = ",",
                                    replacement = ".")) %>% 
  mutate(pct_elevated = as.numeric(pct_elevated))


```

```{r}

ggplot(data = stl_blood, aes(x = prop_white, y = pct_elevated)) + 
  geom_point(aes(color = prop_white), show.legend = FALSE) + 
  scale_color_gradient(low = "blue", high = "orange") + 
  labs(title = "Elevated Lead Blood Levels by Race",
                                                                                                                        x = "Percentage of Census Identifying as White", 
                                                                                                                        y = "Percentage of Children with Elevated Lead Blood Levels")

```


```{r}
ggplot(data = stl_blood, aes(x = pct_elevated)) +
  geom_histogram(aes(color = "orange", alpha = 0.5, fill = "pink"), show.legend = FALSE) +
  theme_minimal() +
  labs(title = "Elevated Levels of Lead in Blood", x = "Elevated Percentage")
```
